Update interview-checklist.md
18F/guides pull request #201
Opened 2023-11-20 16:18 UTC by melchoyce

Remove reference to checkboxes since we have an issue for that: https://github.com/18F/TLC-crew/issues/379

2023-11-20 17:08 UTC, jskinne3 requested changes

2023-11-20 17:08 UTC, jskinne3 commented on content/ux-guide/resources/interview-checklist.md
> +Note that the permalink here does not include /resources/ so there's no indication where this page actually sits.. This content is also very similar (or identical) to the Interview Checklist at https
Extra `.`

2023-11-20 21:50 UTC, melchoyce commented
@jskinne3 Can I have you recheck this?

2023-11-20 23:56 UTC, jskinne3 approved these changes

2023-11-21 16:20 UTC, alexsobledotgov commented
Reviewed! Approved! I'm hitting merge! Thanks @melchoyce @jskinne3!

2023-11-21 16:20 UTC, merged