476 updates
18F/guides pull request #607
Opened 2024-06-17 18:18 UTC by mitogi

## Changes proposed in this pull request:

1. Added sticky leftmost column and a max-width condition
2. Cleaned up punctuation
3. Moved table description above
4. Added back to blueprint button

!. changed use case from "burger" to "getting fast food"
2. edited table content for clarity

##considerations

had to change the dark green border on first table cell to same color as rest of table. Otherwise the dark green get overlapped with light green border when sticky column feature is scrolled.

2024-06-18 17:34 UTC, mitogi commented on content/methods/service-blueprint-example.md
> +      <a class="usa-button usa-button--base" href="/methods/decide/service-blueprint/">Back to Service Blueprint Methods</a>
changed

2024-06-18 17:37 UTC, mitogi commented on content/methods/service-blueprint-example.md
> +        <p class="caption">This is a table showing an example service blueprint. The top row is the journey of a customer ordering and eating at a fast food restaurant. Each column is a different ste
done

2024-06-20 16:33 UTC, cantsin commented
Checking on status here; do we need more review @sam-couch-18f @mitogi ?

2024-07-01 20:27 UTC, MelissaBraxton commented
Hi @mitogi  - I get a 404 when I try and use the "back to blueprint" button in the preview. Once that's fixed, it looks good to me!

2024-07-02 19:35 UTC, MelissaBraxton requested changes
I get a 404 when trying to use the "return to blueprint" button when I checked this out on th Pages preview. Once that's fixed, I think this'll be good to go!

2024-07-02 19:41 UTC, mitogi commented
Updated to link for Back to service blueprint button. Should work now. Thanks for catching that, Melissa!

2024-07-09 18:21 UTC, MelissaBraxton approved these changes
Looks good to me!

2024-07-09 18:25 UTC, merged