method, qual data analysis
18F/guides pull request #609
Opened 2024-06-18 17:00 UTC by a-chappelear

## Changes proposed in this pull request:

Adding Qual data method per tlc ticket #470

## security considerations

[Note the any security considerations here, or make note of why there are none]

None

2024-06-18 19:02 UTC, juliaklindpaintner requested changes
Hey there! I noted a few elements that I think should be changed for consistency before publishing. 

I have an overarching question that really is more in relation to [the original ticket](https://github.com/18F/guides/issues/408) for content creation, so since that has already been approved, I don't think it has to be a blocker to completing the implementation ticket. But it seems to me that the content here is too high-level to be helpful and very close to the Affinity mapping method. The original ticket was meant to provide instructions for "coding qualitative research data," which I don't think this card really does. I'll tag in @bpdesigns and @MelissaBraxton to weigh in on whether these concerns need to be addressed before publishing this new method card.

2024-06-18 19:12 UTC, MelissaBraxton commented
I agree with Julia's comment that I think we can add a little more detail to make this more actionable. As is, it reads a lot like affinity mapping. I'd encourage folks to start by reading through Boon's great, brief, yet practical guide on [coding qual data](https://docs.google.com/document/d/1P3R2N5y1os-OyKIkKHnTaVGqlIxpHP_gLWtsSL0fTSs/edit). I think we could improve the helpfulness of this card if we include some of the details re: coding data, sorting/sifting, recoding to draw out themes.

2024-06-18 21:07 UTC, bpdesigns commented on content/methods/decide/qualitative-data-analysis.md
> +  parent: Decide
@cantsin do you know if adding a dropdown here is manually coded?

2024-06-18 21:09 UTC, bpdesigns commented
Thank you @juliaklindpaintner and @MelissaBraxton for your review! 

@a-chappelear we will need to update the content on this ticket in light of these reviews. Would you like to take on the content changes for this ticket or just own the implementation?

2024-06-18 21:52 UTC, a-chappelear commented
@bpdesigns I would move this ticket as blocked and [re-open the content ticket](Qualitative data analysis) for it (I agree, it seems similar to the affinity card, many items in that category could be considered a form of qual data analysis...maybe it belongs in a diff category) I'm happy to adjust, & perhaps consult with Boon and/or IA folks if available.

2024-06-21 15:51 UTC, cantsin commented on content/methods/decide/qualitative-data-analysis.md
> +  parent: Decide
Yes. These are defined in `_data/navigation.yaml`

2024-07-15 18:28 UTC, a-chappelear commented
PR pushed, with reworked content per https://github.com/orgs/18F/projects/41/views/1?pane=issue&itemId=23668884

2024-07-15 18:33 UTC, MelissaBraxton commented
@a-chappelear - I'm concerned about the mention of specific proprietary tools (Airtable, Excel) as well as links under resources to for-profit sites. We've been told by OGC that we can't appear to be endorsing products/companies, so I think all refs to proprietary stuff needs to be removed or replaced.  We could revise the content under "why" to just say something about spreadsheet tools...

2024-07-19 16:25 UTC, MelissaBraxton approved these changes
LGTM!

2024-07-22 15:46 UTC, a-chappelear commented
This is ready - but it seems like it needs an approve from @juliaklindpaintner due to comments/resolved.

2024-09-23 14:31 UTC, edwintorres commented
Hi @juliaklindpaintner 

 Could you please review your review request to see if it’s done or dismiss it if it’s no longer needed?

2024-09-23 20:07 UTC, merged