Apply consistent naming convention to resource titles
18F/guides pull request #624
Opened 2024-06-21 18:41 UTC by alia-salim

### From: [Make UX Guide resource titles consistent and easy to recognize in search results #402](https://github.com/18F/guides/issues/402)

Applies a consistent naming convention to the 12 pages identified as "resources" in [Claire's content audit of the UX guide.](https://docs.google.com/spreadsheets/d/1QQy8wIx0W3Ne_X7aJAu8xGPvrJqzG8L-vc4OShnxLMM/edit#gid=1993969001)

The previous titles did not follow a consistent format (e.g., "Name of resource [template]"; "Name of resource -- Topic").

The proposed naming convention is "Resource: [Name of resource]".

## Changes proposed in this pull request:

Title changes to 12 UX Guide pages:
- resources/research-plan
- usability-test-quality-heuristics
- resources/privacy-act-notice
- participant-agreement
- participant-agreement-spanish
- interview-checklist/
- interview-script
- interview-debrief
- usability-test-script/
- resources/email-templates/stakeholder-introduces-researcher
- resources/email-templates/researcher-introduces-themselves
- resources/email-templates/researcher-sends-agreement

## security considerations

None

2024-06-21 21:30 UTC, claireb-gsa reviewed
A question about the email templates

2024-06-21 21:30 UTC, claireb-gsa commented on content/ux-guide/resources/email-templates/researcher-sends-agreement.md
@alia-salim The change to the title drops the fact that it's an email... that seems helpful context to me. What do you think?

2024-06-24 15:11 UTC, alia-salim commented on content/ux-guide/resources/email-templates/researcher-sends-agreement.md
@claireb-gsa Absent a deliberate keyword strategy, in titles I'm generally aiming for "as little as possible, as much as necessary" -- and to my read there isn't really anything about the content that makes it understandable or useful *only* as an email. That said, no strong opinions -- if that detail is important to keep, I'd suggest:

`Resource: Researcher introduction email
`

-- for length and for consistency with the other page titles. Let me know if that'd work, or if something else sounds good to you!

2024-06-24 16:28 UTC, claireb-gsa commented on content/ux-guide/resources/email-templates/researcher-sends-agreement.md
I think part of what I'm reacting to is that the email titles sound different from the others, which are much more oriented  to the object: a checklist, a guide, an agreement, template. These read more like an action.

With your proposal, they read more consistently to me:
Resource: Researcher introduction email
Resource: Participant agreement email (to distinguish from the actual agreement) 
Resource: Researcher introduction email from stakeholder (?)

2024-06-24 16:59 UTC, alia-salim commented on content/ux-guide/resources/email-templates/researcher-sends-agreement.md
@claireb-gsa That makes sense! I'll update those three titles.

2024-06-24 19:51 UTC, claireb-gsa approved these changes

2024-06-24 20:39 UTC, bpdesigns requested changes
Looks good! Just one comment

2024-06-24 20:39 UTC, bpdesigns commented on content/ux-guide/resources/participant-agreement-spanish-no-compensation.md
Should "Resource"" be in Spanish? Or "Resource/Recurso:"  (if that is the right word in Spanish)

2024-06-24 20:52 UTC, alia-salim commented on content/ux-guide/resources/participant-agreement-spanish-no-compensation.md
@bpdesigns I'm not sure! This appears to be the only page in the guide offered in Spanish, so I don't think there's a convention to follow. When I think about who's likely to be looking for a resource like this, I think it might actually make more sense to put the entire title in English ("Resource: Design research participant agreement in Spanish"). @claireb-gsa , what do you think?

2024-06-25 15:09 UTC, claireb-gsa commented on content/ux-guide/resources/participant-agreement-spanish-no-compensation.md
ooooo a good question - yeah, I think having the navigational page title in english makes sense. 

However, so the context of the doc is still there, can we add the current title as a page-level header? That way it's still possible to come up in search.

Contrato para participantes en el Estudio de Investigación (sin pagar)

2024-06-25 17:35 UTC, alia-salim commented on content/ux-guide/resources/participant-agreement-spanish-no-compensation.md
@claireb-gsa Ok! I think I've made those changes, but the process of editing my own previous edits is starting to push the (very low) limit of my beginner Github skills -- please let me know if I haven't done this right.

2024-06-27 21:35 UTC, bpdesigns approved these changes

2024-09-19 18:50 UTC, nateborr commented
This change was reviewed thoroughly in June 2024 and expected to be in production already. I've resolved a minor merge conflict and will merge now.

2024-09-19 18:51 UTC, merged