Create a new method card for systems mapping
18F/guides pull request #625
Opened 2024-06-24 20:53 UTC by allisonpress

Adding a new method card for systems mapping to the 18F methods page.

## Changes proposed in this pull request:

- Adding a new card about systems mapping to the "discover" section of the 18F methods page

## security considerations

None

2024-06-25 15:10 UTC, beechnut requested changes

2024-06-25 15:10 UTC, beechnut commented on content/methods/discover/system-map.md
> +  ---
It looks like there's a space before the `---` that would mark the end of the frontmatter and the start of the content.

[This error](https://github.com/18F/guides/actions/runs/9652280246/job/26622055956#step:6:18) seems to be saying that L21 is still being interpreted as frontmatter.

I think if you delete the leading space on L19, it'll build.

2024-06-25 17:26 UTC, bpdesigns approved these changes
LGTM! @allisonpress

2024-06-25 20:25 UTC, bpdesigns approved these changes

2024-06-27 17:27 UTC, beechnut approved these changes

2024-06-27 17:27 UTC, merged