archetypes added
18F/guides pull request #642
Opened 2024-07-08 00:44 UTC by a-chappelear

## Changes proposed in this pull request:

- Archetype method card added, persona removed, navigation updated. Links updated on research page.
-
-

## security considerations

[Note the any security considerations here, or make note of why there are none]

2024-07-08 00:49 UTC, a-chappelear commented
Ticket - #289 ; the only link I found referring to the persona method was on https://guides.18f.gov/ux-guide/research/make-research-actionable/

https://guides.18f.gov/ux-guide/research/plan/, this mentions personas but it’s linking to a blog post (not the method card)

2024-07-09 18:10 UTC, MelissaBraxton commented on content/methods/decide/archetypes.md
> +  why: Unlike demographic data that can explicitly introduce creative blocks or bias, archetypes can help better understand product or service users who share the same core desires.
Replace the word "explicitly" with "unintentionally"

2024-07-09 18:13 UTC, MelissaBraxton requested changes
A few tiny word additions. Otherwise, looks good to me!

2024-07-09 18:13 UTC, MelissaBraxton commented on content/methods/decide/archetypes.md
> +  why: Unlike demographic data that can explicitly introduce creative blocks or bias, archetypes can help better understand product or service users who share the same core desires.
Include "behaviors" in the last sentence: "...users who share the same behaviors and core desires."

2024-07-10 15:21 UTC, a-chappelear commented
Updated w/ edits!

2024-07-23 15:37 UTC, a-chappelear commented
> @a-chappelear Looking good! I hate to say it, but we need to remove the NN link too, since they offer training for $. After that, I think we're good to go!

updated!

2024-07-23 16:55 UTC, MelissaBraxton approved these changes
LGTM!

2024-08-01 01:22 UTC, merged