Changed Open Peeps to 18F Folks
18F/guides pull request #722
Opened 2024-09-17 20:50 UTC by mitogi

Changed Open Peeps to _18F Folks_. Peeps is the trademarked marshmallow.

## Changes proposed in this pull request:

-
-
-

## security considerations

[Note the any security considerations here, or make note of why there are none]

2024-09-23 21:15 UTC, nateborr commented
@mitogi Is your intent to apply a change to the main branch and deploy it? Currently this PR is set to make a one-word change to the `mp-open-peeps-add` branch in the 18F repo from the branch with the same name in your fork of the repo.

If so, if you click the Edit button at the top of the PR, you'll see a drop-down that will give you the option to change the base branch of the PR (that is, the branch that will receive the change you're proposing) to main.

If you'd like to pair on making the change, let me know and I'd be happy to!

2024-09-26 15:55 UTC, igorkorenfeld requested changes
Looking good – one minor spacing change, and a content change to consider.

2024-09-26 15:55 UTC, igorkorenfeld commented on content/brand/images.md
> +
Let's remove this extra space to match the reminder of the doc

2024-09-26 15:55 UTC, igorkorenfeld commented on content/brand/images.md
> +In order to represent a more diverse spectrum of human experiences, we’ve adopted an illustration style called *18F Folks*.
> we’ve adopted an illustration style called *18F Folks*.

This line reads a little funny to me. I think 18F Folks refers to the customizable library, not necessarily the style. Much in the same way Open Peeps itself is called a library and not a style – even if it clearly uses a particular and consistent style.  So my suggestion  is something more like "We've created a library called "18F Folks, based on Pablo Stanley's..."

2024-10-22 14:05 UTC, igorkorenfeld approved these changes
Changes look good!

2025-01-06 19:18 UTC, michelle-rago commented on content/brand/images.md
> +In order to represent a more diverse spectrum of human experiences, we’ve adopted an illustration style called *18F Folks*.
I think the new text is good, right?

2025-01-08 22:04 UTC, igorkorenfeld approved these changes
Looks good to me, feel free to merge when ready!

2025-01-08 22:15 UTC, michelle-rago commented
> Looks good to me, feel free to merge when ready!

Darn. This requires commits to be signed. I don't have that set up. You can merge if you're able, @igorkorenfeld!

2025-01-10 18:57 UTC, igorkorenfeld commented
Superseded by #776

2025-01-10 18:57 UTC, closed without merging